services:
  elasticsearch:
    environment:
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      VIRTUAL_HOST: ${VIRTUAL_HOST}
    networks:
      - step-ca-network

networks:
  step-ca-network:
    name: step-ca-network
    external: true
